typography_spectrum: 0.7943052710033953
color:
  brandStrength: 0.3461558292619884
  lightness: 0.22423389786854386
  saturation: 0.92436582618393
  rhythmicContrast: 0.311841681599617
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.6706408823374659
name: James Wallace
title: James Wallace
description: Human
